name: Detect token via gitleaks
on:
  pull_request:
    branches:
      - main
      - develop
      - master
  push:
    branches:
      - main
      - develop
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v1
        with:
          fetch-depth: '0'

      - name: Gitleaks scanner running
        id: gitleaks
        uses: Dehaat/gitleaks-action@master
        with:
          fail: false

      - name: Notify Token Detected
        if: steps.gitleaks.outputs.exitcode == 1
        uses: voxmedia/github-action-slack-notify-build@v1
        id: slack
        with:
          channel_id: C03CB550DRD
          status: Token Detected. Check Report at workflow.
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
